#!/usr/bin/env bash

set -eu
[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx
syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }

(( $# != 3 )) && {
   syntax_error "$0 <host> <interval>"
}

declare -r HOST=$1 INTERVAL=$2 MAXTRY=$3
declare -i attempts=0
check_ping() {
  local hostname=$1
  ping -c 1 -w 5 "$hostname" | grep -q ^64
  return $?
}
progress_tic() { if [[ -t 1 ]]; then printf -- "%s" "$@"; else printf -- "%s\n" "$@" ;  fi ; }

while (( attempts <= MAXTRY ))
do
    if ! check_ping "$HOST"
       then  progress_tic "."; # output a progress string.
    else  echo "OK: Ping return from  $HOST" && break; # successful.
    fi
    (( attempts += 1 ))  ; # increment counter for the failed attempt.
    (( attempts == MAXTRY )) && {
      printf >&2 "\nReached max tries: $attempts. No reply from $HOST %s. Exiting.\n" "$PORT"
      exit 1
    }
    sleep "$INTERVAL"
done
exit $?
